version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      DB_NAME: orders_db
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: orders_db
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data: